Feature/user service
nathanformentin/desafio-spring pull request #3
Opened 2021-07-07 18:49 UTC by nathanformentin

Foi desenvolvido o serviço para operações relacionadas ao Usuário. Foi também necessário adicionar construtores para o devido funcionamento, visto que o Lombok não trabalha com o super().

As funções já foram testadas de forma básica, aguardando code review/melhorias.

2021-07-07 20:16 UTC, JhonasML requested changes

2021-07-07 20:16 UTC, JhonasML commented on src/main/java/com/mercadolivre/desafio_spring/service/UserService.java
> +        }
dar update nos usuarios via repository

2021-07-07 20:16 UTC, JhonasML commented on src/main/java/com/mercadolivre/desafio_spring/service/UserService.java
> +        if (order.equals("name_desc")) {
Adicionar string como constant na classe

`private static final String NAME_DESC = "name_desc";`

2021-07-07 20:16 UTC, JhonasML commented on src/main/java/com/mercadolivre/desafio_spring/service/UserService.java
> +    private List<UserDTO> getAllSorted(List<Integer> followersIds, String order) {
Melhorar o nome do método

2021-07-08 14:00 UTC, JhonasML approved these changes
chique 10

2021-07-08 14:10 UTC, vicrodrigues96 approved these changes

2021-07-08 15:22 UTC, merged